"""C&E Exporter (Plan §10) — render the UFP Cause & Effect draft.

Output layout, matching the UFP C&E sheet (Plan §10.2 + the Fairless Hills read file):
  - 4 leading text columns: Note, Cause, Alarm, Setpoint
  - Sequence-control columns: one Treat{N} per active cylinder, one Mix{N} per
    mix system — sized to the Plant Configuration (Plan §7.4)
  - One column per non-excluded device that has an output, rendered with its
    C&E output-tag name via the Naming Rule Engine
  - Rows generated by the UFP cause library, scaled to the plant

The output is a fresh workbook (`{SiteName}_CauseAndEffect_Draft.xlsx`) with
one sheet `C&E`. A legend block sits above the matrix for the engineer.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from backend.ingest import IngestedSheet, SheetKind, ingest_workbook
from backend.model import DeviceClass, DeviceModel, ReviewStatus
from backend.model.device import DeviceRecord
from backend.model.plant import PlantConfiguration
from backend.naming import ce_output_tag
from backend.profiles import (
	CEProfile,
	CauseRow,
	get_ufp_ce_profile,
)
from backend.profiles.ufp_ce import (
	_active_cylinder_numbers,
	_eligible_devices,
	_mix_numbers,
	mix_col,
	treat_col,
)


# Device classes that get an output column in the C&E.
_DEVICE_CLASSES_WITH_OUTPUT = {
	DeviceClass.VALVE,
	DeviceClass.CONTROL_VALVE,
	DeviceClass.PUMP,
	DeviceClass.VFD_PUMP,
}


def _safe_site_name(plant: PlantConfiguration) -> str:
	base = plant.site_name.strip() or "Project"
	return "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in base)


def _sorted_devices_for_columns(devices: list[DeviceRecord]) -> list[DeviceRecord]:
	"""Stable ordering for the device-output columns."""
	included = [
		d for d in _eligible_devices(devices)
		if d.device_class in _DEVICE_CLASSES_WITH_OUTPUT
	]
	return sorted(
		included,
		key=lambda d: (d.system.value, d.system_number or 0, d.device_class.value, d.base_name.lower()),
	)


def _build_column_order(plant: PlantConfiguration, devices: list[DeviceRecord]) -> list[tuple[str, str]]:
	"""Return [(column_key, header_label), ...] for every output column.

	column_key is what CauseRow.effects keys against — `Treat:N`, `Mix:N`, or
	a device.canonical_id. header_label is what the human sees at the top of
	the column.
	"""
	out: list[tuple[str, str]] = []
	for n in _active_cylinder_numbers(plant):
		out.append((treat_col(n), f"Treat {n} Pause"))
	for n in _mix_numbers(plant):
		out.append((mix_col(n), f"Mix {n} Pause"))
	for d in _sorted_devices_for_columns(devices):
		out.append((d.canonical_id, ce_output_tag(d)))
	return out


def _build_rows(
	profile: CEProfile, plant: PlantConfiguration, devices: list[DeviceRecord]
) -> list[CauseRow]:
	rows: list[CauseRow] = []
	for gen in profile.generators:
		rows.extend(gen(plant, devices))
	return rows


_HEADER_FILL = PatternFill(start_color="FFE8EEF7", end_color="FFE8EEF7", fill_type="solid")
_LEGEND_FILL = PatternFill(start_color="FFF6F6F6", end_color="FFF6F6F6", fill_type="solid")


def _write_legend(ws, start_row: int) -> int:
	ws.cell(row=start_row, column=1).value = "Legend"
	ws.cell(row=start_row, column=1).font = Font(bold=True)
	pairs = [
		("P", "Pause — prevent the sequence from starting"),
		("C", "Close (valve)"),
		("O", "Open (valve)"),
		("E", "Energize"),
		("D", "De-Energize"),
		("A", "Alarm"),
		("SA", "System Active — see Sequence Matrix"),
	]
	for i, (code, meaning) in enumerate(pairs, start=1):
		ws.cell(row=start_row + i, column=1).value = code
		ws.cell(row=start_row + i, column=2).value = meaning
		ws.cell(row=start_row + i, column=1).fill = _LEGEND_FILL
		ws.cell(row=start_row + i, column=2).fill = _LEGEND_FILL
	return start_row + len(pairs) + 2  # blank row before the matrix


def _write_header(ws, header_row: int, columns: list[tuple[str, str]]) -> None:
	headers = ["Note", "Cause", "Alarm", "Setpoint"] + [label for _, label in columns]
	for c, h in enumerate(headers, start=1):
		cell = ws.cell(row=header_row, column=c)
		cell.value = h
		cell.font = Font(bold=True)
		cell.fill = _HEADER_FILL


def _write_rows(ws, first_row: int, columns: list[tuple[str, str]], rows: list[CauseRow]) -> int:
	col_keys = [k for k, _ in columns]
	for ri, row in enumerate(rows):
		r = first_row + ri
		ws.cell(row=r, column=1).value = row.note
		ws.cell(row=r, column=2).value = row.cause
		ws.cell(row=r, column=3).value = row.alarm
		ws.cell(row=r, column=4).value = row.setpoint
		for ci, key in enumerate(col_keys):
			value = row.effects.get(key, "")
			if value:
				ws.cell(row=r, column=5 + ci).value = value
	return first_row + len(rows)


def _autosize_first_columns(ws, columns: list[tuple[str, str]]) -> None:
	# Cause / setpoint columns benefit from a wider width; effect columns get
	# a narrow uniform width so the matrix stays scannable.
	widths = [22, 32, 8, 22] + [16] * len(columns)
	for i, w in enumerate(widths, start=1):
		ws.column_dimensions[get_column_letter(i)].width = w


def _write_ce_sheet(wb: openpyxl.Workbook, plant: PlantConfiguration, model: DeviceModel, profile: CEProfile) -> None:
	"""Build the original C&E matrix sheet on the supplied workbook."""
	# Replace the default sheet (which openpyxl creates as "Sheet") with our
	# named one. Re-using the active sheet keeps the workbook compact.
	ws = wb.active
	ws.title = "C&E"

	# Title row
	ws.cell(row=1, column=1).value = f"{plant.site_name} — Cause & Effect Draft"
	ws.cell(row=1, column=1).font = Font(bold=True, size=14)
	if plant.erp_number:
		ws.cell(row=1, column=2).value = f"ERP #{plant.erp_number}"

	header_row = _write_legend(ws, start_row=3)

	columns = _build_column_order(plant, model.devices)
	rows = _build_rows(profile, plant, model.devices)
	_write_header(ws, header_row, columns)
	_write_rows(ws, header_row + 1, columns, rows)

	_autosize_first_columns(ws, columns)
	# Freeze the leading 4 text columns + the header row.
	ws.freeze_panes = f"E{header_row + 1}"


# =============================================================================
# Sequence Sign-Off tabs
# =============================================================================
# Layout matches the UFP commission workbook's "Treat Sequence Sign Off" and
# "Mix Sequence Sign Off" sheets (FairlessHills_CommWKBK_033026.xlsx). The
# engineer signs off step-by-step during commissioning.
_SIGN_OFF_HEADERS = ["System", "Step", "Description", "UFP Sign-off", "TAS Sign-off", "Date", "Notes"]
_SIGN_OFF_WIDTHS = [12, 6, 80, 14, 14, 12, 30]


def _is_step_header(line: str) -> bool:
	"""A heuristic: lines that look like step headers ("STEP 1 — Initial Vacuum")
	get bolded so the sign-off doc reads like the original.
	"""
	upper = line.upper().strip()
	return upper.startswith(("STEP ", "PHASE ", "MODE ")) or upper.endswith(":")


def _format_label(sheet: IngestedSheet) -> str:
	"""Render a short System label for the first column ("Cyl 1", "ECO Mix")."""
	if sheet.kind == SheetKind.CYLINDER_SEQUENCE and sheet.cylinder_number is not None:
		return f"Cyl {sheet.cylinder_number}"
	if sheet.kind == SheetKind.MIX_SEQUENCE:
		return (sheet.mix_label or "Mix").strip() or "Mix"
	return sheet.name


def _write_sign_off_sheet(
	ws,
	title: str,
	plant: PlantConfiguration,
	sheets: list[IngestedSheet],
) -> int:
	"""Populate a sign-off worksheet with all the prose lines from `sheets`.

	One row per non-empty line. Step-header-looking lines are bolded. Returns
	the total number of data rows written (informational).
	"""
	# Title
	ws.cell(row=1, column=1).value = f"{plant.site_name} — {title}"
	ws.cell(row=1, column=1).font = Font(bold=True, size=14)
	if plant.erp_number:
		ws.cell(row=1, column=4).value = f"ERP #{plant.erp_number}"

	header_row = 3
	for i, h in enumerate(_SIGN_OFF_HEADERS, start=1):
		c = ws.cell(row=header_row, column=i)
		c.value = h
		c.font = Font(bold=True)
		c.fill = _HEADER_FILL

	for i, w in enumerate(_SIGN_OFF_WIDTHS, start=1):
		ws.column_dimensions[get_column_letter(i)].width = w

	r = header_row + 1
	written = 0
	for sheet in sheets:
		label = _format_label(sheet)
		lines = sheet.text_lines()
		step_counter = 0
		# Section break row — bold, full-width label
		section = ws.cell(row=r, column=1)
		section.value = f"{label}  ({sheet.name})"
		section.font = Font(bold=True, italic=True)
		section.fill = _LEGEND_FILL
		for col in range(2, len(_SIGN_OFF_HEADERS) + 1):
			ws.cell(row=r, column=col).fill = _LEGEND_FILL
		r += 1

		for line in lines:
			step_counter += 1
			ws.cell(row=r, column=1).value = label
			ws.cell(row=r, column=2).value = step_counter
			desc_cell = ws.cell(row=r, column=3)
			desc_cell.value = line
			desc_cell.alignment = Alignment(wrap_text=True, vertical="top")
			if _is_step_header(line):
				desc_cell.font = Font(bold=True)
			r += 1
			written += 1

		# Blank spacer row between sheets for readability
		r += 1

	# Freeze the header so it stays visible while scrolling.
	ws.freeze_panes = f"A{header_row + 1}"
	return written


def _load_workbook_sheets(plant: PlantConfiguration, sequence_workbook_path: Optional[Path]) -> list[IngestedSheet]:
	"""Re-ingest the source workbook to access the sequencing prose.

	The ingester is cheap; running it again here keeps `export_ce` self-
	contained (it doesn't have to be threaded a workbook object through the
	router). Returns an empty list if the workbook is missing.
	"""
	if sequence_workbook_path is None or not Path(sequence_workbook_path).exists():
		return []
	wb = ingest_workbook(sequence_workbook_path)
	return [s for s in wb.sheets if s.kind in (SheetKind.CYLINDER_SEQUENCE, SheetKind.MIX_SEQUENCE)]


def export_ce(
	plant: PlantConfiguration,
	model: DeviceModel,
	output_dir: str | Path,
	profile: Optional[CEProfile] = None,
	sequence_workbook_path: Optional[Path] = None,
) -> Path:
	"""Render the C&E workbook and save it.

	The output is a multi-tab xlsx:
	  - "C&E"                     : the cause / effect matrix
	  - "Treat Sequence Sign Off" : cylinder sequence prose, step-by-step
	  - "Mix Sequence Sign Off"   : mix-system sequence prose, step-by-step

	The two sign-off sheets are populated from the prose in the supplied
	source workbook. They give the commissioning engineer the same
	step-by-step sign-off layout used in the UFP commission workbook.
	"""
	if profile is None:
		profile = get_ufp_ce_profile()

	wb = openpyxl.Workbook()
	_write_ce_sheet(wb, plant, model, profile)

	sequence_sheets = _load_workbook_sheets(plant, sequence_workbook_path)
	cylinder_sheets = [s for s in sequence_sheets if s.kind == SheetKind.CYLINDER_SEQUENCE]
	mix_sheets = [s for s in sequence_sheets if s.kind == SheetKind.MIX_SEQUENCE]

	if cylinder_sheets:
		ws = wb.create_sheet("Treat Sequence Sign Off")
		_write_sign_off_sheet(ws, "Treat Sequence Sign Off", plant, cylinder_sheets)
	if mix_sheets:
		ws = wb.create_sheet("Mix Sequence Sign Off")
		_write_sign_off_sheet(ws, "Mix Sequence Sign Off", plant, mix_sheets)

	out_dir = Path(output_dir)
	out_dir.mkdir(parents=True, exist_ok=True)
	out_path = out_dir / f"{_safe_site_name(plant)}_CauseAndEffect_Draft.xlsx"
	wb.save(out_path)
	return out_path
