"""Dry-run Prose Extractor — no network, no API key.

Used by the browser ?demo=extract path and as a safe default while Open Q 6
(UFP data-policy sign-off for sending prose to the Claude API) is still open.
The extractor returns deterministic, plausible-looking devices for each sheet
so the Extract screen can be exercised end-to-end without touching the real
API or any real customer data.

Failure simulation:
  - Construct with `fail_first_attempt={"<sheet name>", ...}` to make the first
    call for those sheets raise ProseExtractionError. A subsequent call (retry)
    will succeed. This is what powers the "fail → retry → recover" demo on the
    Extract screen.
"""

from __future__ import annotations

import asyncio
import re
from typing import Optional

from backend.model.device import (
	Confidence,
	DeviceClass,
	DeviceRecord,
	SourceType,
	SystemKind,
)

from .prose import (
	ProseExtractionError,
	ProseExtractor,
	ProseSource,
	SheetExtraction,
)


def _canonical_id(system: SystemKind, system_number: Optional[int], base_name: str) -> str:
	sys_tag = "CYL" if system == SystemKind.CYLINDERS else "MIX"
	num = str(system_number) if system_number is not None else "X"
	clean = re.sub(r"[^A-Za-z0-9]+", "", base_name).upper() or "UNNAMED"
	return f"{sys_tag}{num}_{clean}"


# A small, plausible device pattern per system kind. Real plants have more,
# but the goal here is a visible, deterministic result, not a faithful sim.
_CYLINDER_PATTERN: list[tuple[str, DeviceClass, str, Confidence]] = [
	("P1", DeviceClass.VFD_PUMP, "Pressure pump", Confidence.HIGH),
	("VPD", DeviceClass.VALVE, "Pressure pump discharge valve", Confidence.HIGH),
	("V9", DeviceClass.VALVE, "Vacuum break valve", Confidence.NEEDS_REVIEW),
	("CV1", DeviceClass.CONTROL_VALVE, "Recirc control valve", Confidence.HIGH),
]
_MIX_PATTERN: list[tuple[str, DeviceClass, str, Confidence]] = [
	("MP1", DeviceClass.PUMP, "Concentrate transfer pump", Confidence.HIGH),
	("MV1", DeviceClass.VALVE, "Mix tank inlet valve", Confidence.HIGH),
	("MCV1", DeviceClass.CONTROL_VALVE, "Blend control valve", Confidence.NEEDS_REVIEW),
]


class DryRunProseExtractor(ProseExtractor):
	def __init__(
		self,
		fail_first_attempt: Optional[set[str]] = None,
		per_call_delay_s: float = 0.4,
	) -> None:
		self._fail_first_attempt = set(fail_first_attempt or [])
		self._attempts: dict[str, int] = {}
		self._delay = per_call_delay_s

	def extract_sheet(self, source: ProseSource) -> SheetExtraction:
		# Block briefly so the Extract screen shows a visible "running" state.
		# This runs inside asyncio.to_thread when driven from the pipeline.
		import time

		time.sleep(self._delay)

		attempt = self._attempts.get(source.sheet_name, 0) + 1
		self._attempts[source.sheet_name] = attempt

		if attempt == 1 and source.sheet_name in self._fail_first_attempt:
			raise ProseExtractionError(
				f"Simulated dry-run failure on '{source.sheet_name}'. Retry will succeed."
			)

		if source.is_empty:
			return SheetExtraction(
				sheet_name=source.sheet_name,
				system=source.system,
				system_number=source.system_number,
				notes=["Sheet had no prose content; nothing to extract."],
			)

		pattern = (
			_CYLINDER_PATTERN if source.system == SystemKind.CYLINDERS else _MIX_PATTERN
		)
		devices: list[DeviceRecord] = []
		for base_name, dc, description, conf in pattern:
			devices.append(
				DeviceRecord(
					canonical_id=_canonical_id(source.system, source.system_number, base_name),
					device_class=dc,
					system=source.system,
					system_number=source.system_number,
					base_name=base_name,
					description=description,
					source_reference=source.sheet_name,
					source_type=SourceType.SEQUENCE_PROSE,
					confidence=conf,
				)
			)
		return SheetExtraction(
			sheet_name=source.sheet_name,
			system=source.system,
			system_number=source.system_number,
			devices=devices,
			notes=["Generated by DryRunProseExtractor — no real API call."],
		)

	# Async version mirrors the sync one — pipeline uses asyncio.to_thread on
	# the sync extract_sheet, so this isn't strictly needed. Kept as a no-op
	# override placeholder for future async-native implementations.
	async def aextract_sheet(self, source: ProseSource) -> SheetExtraction:
		await asyncio.sleep(0)
		return self.extract_sheet(source)
